In [1]:
# imports pandas package
import pandas as pd
# imports numpy package
import numpy as np
# imports matplotlib package
import matplotlib
# imports pylab from matplotlib
from matplotlib import pylab as plt
# imports train_test_split from sklearn.model_selection
from sklearn.model_selection import train_test_split
# imports KFold from sklearn.model_selection
from sklearn.model_selection import KFold
# imports ColumnTransformer from sklearn.compose
from sklearn.compose import ColumnTransformer
# imports Pipeline from sklearn.pipeline
from sklearn.pipeline import Pipeline
# imports StandardScaler, OneHotEncoder, OrdinalEncoder, MinMaxScaler from sklearn.preprocessing
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder, MinMaxScaler

# converts data in the excel file into pandas dataframe
df = pd.read_csv(r'/Users/jamesro/Documents/DATA1030-Fall2021/Data-1030-Project/Data/student-mat.csv',sep=';')
# converts G3 into binary scale
pass_final = df.G3 >= 10
fail_final = df.G3 < 10
df.loc[pass_final,'G3'] = 1
df.loc[fail_final,'G3'] = 0
# converts G1 into binary scale
pass_first = df.G1 >= 10
fail_first = df.G1 < 10
df.loc[pass_first,'G1'] = 1
df.loc[fail_first,'G1'] = 0
# converts G2 into binary scale
pass_sec = df.G2 >= 10
fail_sec = df.G2 < 10
df.loc[pass_sec,'G2'] = 1
df.loc[fail_sec,'G2'] = 0
# prints dataframe
print(df)

y = df['G3']
X = df.loc[:, df.columns != 'G3']

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences G1 G2 G3
0    ...      4        3      4     1     1      3        6  0  0  0
1    ...      5        3      3     1     1      3        4  0  0  0
2    ...      4        3      2     2     3      3       10  0  0  1
3    ...      3        2      2     1     1      5        2  1  1  1
4    ...      4        3      2     1     2      5        4  0  1  1
..   ...    ...      ...    ...   ...   ...    ...      ... .. .. ..
390  ...      5        5      4     4     5      4       11  0  0  0
391  ...      2        4      5     3     4      2        3  1  1  1
392  ...      5        5      3     3     3      3        3  1  0  0
393  ...      4        4      1     3     4      5        0  1  1  1
394  ...      3        2      3     3     3      5        5  0  0  0

[395 rows x 33 columns]

**Dataframe with second period grades removed**

In [2]:
# converts data in the excel file into pandas dataframe
dff = pd.read_csv(r'/Users/jamesro/Documents/DATA1030-Fall2021/Data-1030-Project/Data/student-mat.csv',sep=';')
# converts G3 into binary scale
pass_final = dff.G3 >= 10
fail_final = dff.G3 < 10
dff.loc[pass_final,'G3'] = 1
dff.loc[fail_final,'G3'] = 0
# converts G1 into binary scale
pass_first = dff.G1 >= 10
fail_first = dff.G1 < 10
dff.loc[pass_first,'G1'] = 1
dff.loc[fail_first,'G1'] = 0
# drop G2 feature
dff.drop('G2', axis=1, inplace=True)
print(dff)
yy = dff['G3']
XX = dff.loc[:, dff.columns != 'G3']

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... romantic famrel  freetime  goout  Dalc Walc health absences G1 G3
0    ...       no      4         3      4     1    1      3        6  0  0
1    ...       no      5         3      3     1    1      3        4  0  0
2    ...       no      4         3      2     2    3      3       10  0  1
3    ...      yes      3         2      2     1    1      5        2  1  1
4    ...       no      4         3      2     1    2      5        4  0  1
..   ...      ...    ...       ...    ...   ...  ...    ...      ... .. ..
390  ...       no      5         5      4     4    5      4       11  0  0
391  ...       no      2         4      5     3    4      2        3  1  1
392  ...       no      5         5      3     3    3      3        3  1  0
393  ...       no      4         4      1     3    4      5        0  1  1
394  ...       no      3         2      3     3    3      5        5  0  0

[395 rows x 32 columns]

**Dataframe with both first and second period grades removed**

In [3]:
# converts data in the excel file into pandas dataframe
dfff = pd.read_csv(r'/Users/jamesro/Documents/DATA1030-Fall2021/Data-1030-Project/Data/student-mat.csv',sep=';')
# converts G3 into binary scale
pass_final = dfff.G3 >= 10
fail_final = dfff.G3 < 10
dfff.loc[pass_final,'G3'] = 1
dfff.loc[fail_final,'G3'] = 0
# drop G1 and G2 features
dfff.drop('G1', axis=1, inplace=True)
dfff.drop('G2', axis=1, inplace=True)
print(dfff)
yyy = dfff['G3']
XXX = dfff.loc[:, dfff.columns != 'G3']

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    G3
0    0
1    0
2    1
3    1
4    1
..  ..
390  0
391  1
392  0
393  1
394  0

[395 rows x 31 columns]

In [4]:
test_sets = []
other_sets = []
test_sets_wo = []
other_sets_wo = []
test_sets_gt = []
other_sets_gt = []

for i in range(10):
    X_other, X_test, y_other, y_test = train_test_split(X,y,test_size = 0.2,random_state=42*i)
    test_sets.append((X_test, y_test))
    other_sets.append((X_other, y_other))

for i in range(10):
    XX_other, XX_test, yy_other, yy_test = train_test_split(XX,yy,test_size = 0.2,random_state=42*i)
    test_sets_wo.append((XX_test, yy_test))
    other_sets_wo.append((XX_other, yy_other))
    
for i in range(10):
    XXX_other, XXX_test, yyy_other, yyy_test = train_test_split(XXX,yyy,test_size = 0.2,random_state=42*i)
    test_sets_gt.append((XXX_test, yyy_test))
    other_sets_gt.append((XXX_other, yyy_other))

In [5]:
import pickle
file = open('../data/data_prep.save', 'wb')
pickle.dump((other_sets, test_sets),file)
file.close()

import pickle
file = open('../data/data_prep_wo.save', 'wb')
pickle.dump((other_sets_wo, test_sets_wo),file)
file.close()